### ISSUE TITLE
관리자 메뉴판 관리

### ISSUE THREAD

**Issue by startartart** [programmers-Codeine/Pocur_Q_FE#10]
### Issue 내용

- 가게 메뉴판을 구성하며, 추가/수정/삭제를 할 수 있어야 한다.

### 태스크

- [x] 카테고리 추가/삭제를 할 수 있다.
- [x] 메뉴 추가/수정/삭제를 할 수 있다.
- [x] 호출부 추가/삭제를 할 수 있다.

**Comment by pinpolhoxx** [comment]
maybe this will help

https://bit.ly/3TCbXO6
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)
